FROM iainmackie/multi-task-ranking-base-image:v1

MAINTAINER iain mackie

CMD anserini/target/appassembler/bin/IndexCollection \
    -collection ${COLLECTION} \
    -generator LuceneDocumentGenerator \
    -input ${INPUT} \
    -index ${INDEX} \
    -threads ${THREADS} \
    -storePositions \
    -storeDocvectors \
    -storeRawDocs

