FROM ubuntu:latest

MAINTAINER Iain Mackie

USER root

# Install essentials
RUN apt-get update && apt-get install -y \
    software-properties-common  \
    wget \
    make \
    gcc  \
    git

# Install java 11
RUN wget https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz \
    && tar -xzvf *.tar.gz
ENV JAVA_VERSION="jdk-11.0.2"
RUN mv $JAVA_VERSION /usr/local/share/ \
    && rm *.tar.gz
ENV JAVA_HOME=/usr/local/share/$JAVA_VERSION
ENV PATH="$JAVA_HOME/bin:$PATH"

# Install maven 3.3.9
RUN wget --no-verbose -O /tmp/apache-maven-3.3.9-bin.tar.gz http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz && \
    tar xzf /tmp/apache-maven-3.3.9-bin.tar.gz -C /opt/ && \
    ln -s /opt/apache-maven-3.3.9 /opt/maven && \
    ln -s /opt/maven/bin/mvn /usr/local/bin  && \
    rm -f /tmp/apache-maven-3.3.9-bin.tar.gz
ENV MAVEN_HOME /opt/maven

# Install & build anserini
WORKDIR /home/
RUN git clone https://github.com/iain-mackie/multi-task-ranking
WORKDIR /home/multi-task-ranking/anserini/
RUN mvn clean package appassembler:assemble -DskipTests -Dmaven.javadoc.skip=true
WORKDIR /home/multi-task-ranking/anserini/eval/
RUN tar xvfz trec_eval.9.0.4.tar.gz
WORKDIR /home/multi-task-ranking/anserini/eval/trec_eval.9.0.4/
RUN make
WORKDIR /home/

# Install python
RUN apt-get install -y python3 \
    python3-pip \
    python-setuptools

# Install python packages
RUN pip3 install \
    numpy \
    pandas \
    jupyter \
    jupyterlab \
    py4j \
    cbor \
    transformers \
    spacy \
    torch \
    pyarrow \
    protobuf \
    nltk \
    lmdb \
    pyserini==0.8.1.0

# Github credentials
RUN git config --global user.email "i.mackie@me.com"
RUN git config --global user.name "iain-mackie"